type = "webpack"
workers_dev = true
site = { bucket = "build" }
main = "workers-site/index.js"
compatibility_date = "2021-10-20"
name = "aries-dev-relayer-frontend"
route = "aries-dev-relayer.subspace.network/*"

[env.production]
name = "relayer"
route = "testnet-relayer.subspace.network/*"
