import { ParachainProps } from "./interfaces/Parachain";
import { getApiUrl } from "./RpcSettings";
const subspaceWss = getApiUrl();

const kusamaParachains: ParachainProps[] = [
  {
    wss: "wss://kusama.api.onfinality.io/public-ws",
    paraId: 0,
    feedId: 0,
    chain: "kusama",
    chainName: "Kusama",
    web: "https://kusama.network/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://statemine.api.onfinality.io/public-ws",
    paraId: 1000,
    feedId: 1,
    chain: "statemine",
    chainName: "Statemine",
    web: "https://parachains.info/details/statemine",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://karura.api.onfinality.io/public-ws",
    paraId: 2000,
    feedId: 2,
    chain: "karura",
    chainName: "Karura",
    web: "https://acala.network/karura",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://bifrost-parachain.api.onfinality.io/public-ws",
    paraId: 2001,
    feedId: 3,
    chain: "bifrost",
    chainName: "Bifrost",
    web: "https://acala.network/bifrost",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://khala.api.onfinality.io/public-ws",
    paraId: 2004,
    feedId: 4,
    chain: "khala",
    chainName: "Khala",
    web: "https://phala.network/en/khala/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://shiden.api.onfinality.io/public-ws",
    paraId: 2007,
    feedId: 5,
    chain: "shiden",
    chainName: "Shiden",
    web: "https://phala.network/en/shiden/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://moonriver.api.onfinality.io/public-ws",
    paraId: 2023,
    feedId: 6,
    chain: "moonriver",
    chainName: "Moonriver",
    web: "https://moonbeam.foundation/moonriver-token/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://calamari.api.onfinality.io/public-ws",
    paraId: 2084,
    feedId: 7,
    chain: "calamari",
    chainName: "Calamari",
    web: "https://www.calamari.network/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://spiritnet.api.onfinality.io/public-ws",
    paraId: 2086,
    feedId: 8,
    chain: "kilt_spiritnet",
    chainName: "KILT Spiritnet",
    web: "https://www.kilt.io/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://basilisk.api.onfinality.io/public-ws",
    paraId: 2090,
    feedId: 9,
    chain: "basilisk",
    chainName: "Basilisk",
    web: "https://bsx.fi/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://altair.api.onfinality.io/public-ws",
    paraId: 2088,
    feedId: 10,
    chain: "altair",
    chainName: "Altair",
    web: "https://centrifuge.io/altair/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://parallel-heiko.api.onfinality.io/public-ws",
    paraId: 2085,
    chainName: "Parallel Heiko",
    chain: "parallel_heiko",
    feedId: 11,
    web: "https://parallel.fi/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://kintsugi.api.onfinality.io/public-ws",
    paraId: 2092,
    chainName: "Kintsugi BTC",
    chain: "kintsugi",
    feedId: 12,
    web: "https://kintsugi.interlay.io/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://pioneer-1-rpc.bit.country",
    paraId: 2096,
    chainName: "Bit.Country Pioneer",
    chain: "pionner",
    feedId: 13,
    web: "https://bit.country/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://node.genshiro.io",
    paraId: 2024,
    chainName: "Genshiro",
    chain: "genshiro",
    feedId: 14,
    web: "https://genshiro.equilibrium.io/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://us-ws-quartz.unique.network",
    paraId: 2095,
    chainName: "Quartz",
    chain: "quartz",
    feedId: 15,
    web: "https://unique.network/quartz/",
    ecosystem: "kusama",
    subspaceWss,
  },
  {
    wss: "wss://picasso-rpc.composable.finance",
    paraId: 2087,
    chainName: "Picasso",
    chain: "picasso",
    feedId: 16,
    web: "https://picasso.composable.finance/",
    ecosystem: "kusama",
    subspaceWss,
  },
];

const polkadotParachains: ParachainProps[] = [
  {
    wss: "wss://polkadot.api.onfinality.io/public-ws",
    paraId: 2087,
    chainName: "Polkadot",
    chain: "polkadot",
    feedId: 17,
    web: "https://polkadot.network/",
    ecosystem: "polkadot",
    subspaceWss,
  },
];

export const allChains = [...kusamaParachains, ...polkadotParachains];
