name: TypeScript

on: [push, pull_request]

jobs:
  ts-lint-and-build:
    runs-on: ubuntu-20.04
    name: Run eslint, check typescript and run tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm ci
        working-directory: frontend
      - run: npm run lint
        working-directory: frontend
      - run: npm run build
        working-directory: frontend
