name: wrangler-publish
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build App and Wrangler Publish.
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm ci
        working-directory: frontend
      - run: npm run build
        working-directory: frontend
      - run: npm i -g @cloudflare/wrangler
        working-directory: frontend
      - run: 'wrangler publish'
        working-directory: frontend
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
